# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('stime', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description_short', models.CharField(blank=True, max_length=50, null=True)),
                ('description_long', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('divider', models.FloatField(default=1)),
                ('multiplier', models.FloatField(default=1)),
                ('koef', models.FloatField(default=1)),
                ('group', models.IntegerField(default=0)),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Tag'),
        ),
    ]
