# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('stime', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('stime', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hourly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('stime', models.CharField(max_length=30)),
                ('end_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Hourly.end_data+', to='web.Data')),
                ('start_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Hourly.start_data+', to='web.Data')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description_short', models.CharField(blank=True, max_length=50, null=True)),
                ('description_long', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('show', models.BooleanField(default=False)),
                ('increasing', models.BooleanField(default=False)),
                ('variable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description_short', models.CharField(blank=True, max_length=50, null=True)),
                ('description_long', models.CharField(blank=True, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('divider', models.FloatField(default=1)),
                ('multiplier', models.FloatField(default=1)),
                ('koef', models.FloatField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Tag_group'),
        ),
        migrations.AddField(
            model_name='hourly',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Tag'),
        ),
        migrations.AddField(
            model_name='data',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Tag'),
        ),
        migrations.AddField(
            model_name='daily',
            name='end_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Daily.end_data+', to='web.Data'),
        ),
        migrations.AddField(
            model_name='daily',
            name='start_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Daily.start_data+', to='web.Data'),
        ),
        migrations.AddField(
            model_name='daily',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Tag'),
        ),
    ]
