# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='object_id',
        ),
    ]
